substitutions:
  device_name: air-control

esphome:
  name: "${device_name}"
  friendly_name: Air Control

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret AC_api_encryption_key

ota:
  - platform: esphome
    password: !secret AC_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Control Fallback Hotspot"
    password: !secret AC_ap_fallback_password

captive_portal:

uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600
  id: uart_2

sensor:
  - platform: scd4x
    temperature:
      name: "Temperature"
      id: temperature
    co2:
      name: "CO2"
      id: co2
    humidity:
      name: "Humidity"
      id: humidity
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
      id: pm
      accuracy_decimals: 1
    uart_id: uart_2
    update_interval: 20s
  - platform: wifi_signal
    name: "Air quality WiFi Signal Sensor"
    entity_category: diagnostic
    disabled_by_default: true
    update_interval: 60s

switch:
  - platform: gpio
    pin: 12
    id: fan
    restore_mode: ALWAYS_ON
    disabled_by_default: true
    entity_category: diagnostic

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO25
    num_leds: 3
    id: status
    restore_mode: ALWAYS_OFF
    method:
      type: esp32_rmt
      channel: 6

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

button:
  - platform: restart
    name: "Restart ${device_name}"
    disabled_by_default: true
    entity_category: diagnostic
